version: "3.9"
services:
  anon_chat_host:
    build: .
    ports:
      - "8080:8080"
    environment:
      FLASK_SECRET: "57508880beebae48866c9a241a746d9a7b9ffc3b7d6da6075b0039d984b43f51"
      FLASK_DEBUG: True
      CACHE_REDIS_HOST: "anon_redis"
    networks:
      - anon-app
  anon_redis:
    image: "redis:bullseye"
    ports:
      - "6379:6379"
    networks:
      - anon-app
  keyclock:
    image: jboss/keycloak:latest
    volumes:
      - ./imports:/tmp/imports
    environment:
      KEYCLOCK_IMPORT: /tmp/imports/realm-export.json -Dkeycloack.profile.feature.upload_scripts=enabled
    container_name: keycloack
    ports:
      - 8010:8010
networks:
  anon-app:
    driver: bridge
      
